### ISSUE TITLE
Support page formating issues

### ISSUE THREAD

**Issue by lamontacrook** [hlxsites/airlessco#81] opened 2023-01-30 16:01 UTC
Left is franklin.

![image](https://user-images.githubusercontent.com/2071728/215528470-67d17ab6-d81b-4b2f-b53e-e61fe270c0e6.png)

**Comment by helms-charity** [comment] 2023-02-07 15:12
This is a duplicate of issue #57 .

**Closed as completed by helms-charity** 2023-02-07 15:12 UTC
